### ISSUE TITLE
Play button stops working with Audio Playlists

### ISSUE THREAD

**Issue by mlubick** [ableplayer/ableplayer#378]
In Demo/Audio3.html, I find that if I click one of the playlist options that the play button stops working.   I do find that the other buttons still seem to function. For example, if I paused and click "Replay" then that will work.  This is not the case for demo/video15.html. I have found this doesn't work on Windows in the browsers for Chrome, Edge, or Firefox.

Steps:
1. Go to page and click an item in the play list
2. Press play.
3. Press pause.
4. Try to press play again, and you are unable to.

**Comment by terrill** [comment]
@mlubick this was fixed on the develop branch, but hasn't made it to an official release yet. I'll do that soon - a few more bugs to fix first.

**Comment by mlubick** [comment]
@terrill Do you have an estimate as to when the fix will move into the official release?

**Comment by mlubick** [comment]
@terrill Thank you!    The bug looks like it is still present in Firefox.  I've confirmed that it is fixed for Mac and Windows for Edge, IE, Safari, and Chrome.

**Comment by mlubick** [comment]
@terrill Actually it looks like the issue still persists on Safari if the user does not allow the audio to finish playing all the way through.  This issue is not present for Chrome.

**Comment by terrill** [comment]
@mlubick I'm not able to replicate this in Safari with the latest Able Player release. Could it be that you're loading a cached version? I tested with using both the [audio playlist](https://ableplayer.github.io/ableplayer/demos/audio3.html) and [video playlist](https://ableplayer.github.io/ableplayer/demos/video15.html) using Safari 12.1.2 in MacOS Mojave (10.14.6).

**Comment by mlubick** [comment]
@terrill The issue ended up being that I was using metadata instead of captions.  So there is still an issue with how it swaps metadata, but the captions are fine.  I'm sorry for the confusion.
